# Generated by Django 6.0 on 2025-12-16 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='email', max_length=10)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('errorMessage', models.TextField(blank=True, null=True)),
                ('sentAt', models.DateTimeField(auto_now_add=True)),
                ('passengerFlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengers.passengerflight')),
            ],
        ),
    ]
