# Generated by Django 6.0 on 2025-12-21 12:12

import airports.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
        ('tickets', '0002_remove_ticketcomment_userid_ticketcomment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=200)),
                ('airport_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_phone', models.CharField(max_length=20)),
                ('selected_plan', models.CharField(choices=[('1_year', '1 Year License'), ('3_years', '3 Years License'), ('5_years', '5 Years License')], default='1_year', max_length=50)),
                ('official_license', models.FileField(upload_to=airports.models.airport_docs_path)),
                ('commercial_record', models.FileField(blank=True, null=True, upload_to=airports.models.airport_docs_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='airportsubscription',
            old_name='expireAt',
            new_name='expire_at',
        ),
        migrations.RenameField(
            model_name='airportsubscription',
            old_name='planType',
            new_name='plan_type',
        ),
        migrations.RenameField(
            model_name='airportsubscription',
            old_name='startAt',
            new_name='start_at',
        ),
        migrations.RemoveField(
            model_name='airportsubscription',
            name='maxEmployees',
        ),
        migrations.AddField(
            model_name='airport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airportsubscription',
            name='max_employees',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(default='Saudi Arabia', max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='airportsubscription',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.DeleteModel(
            name='AirportUser',
        ),
    ]
