# Generated by Django 5.2.9 on 2025-12-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0006_alter_airport_id_alter_airportsubscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='image',
            field=models.ImageField(blank=True, default='airport_images/default.jpg', null=True, upload_to='airport_images/'),
        ),
    ]
