# Generated by Django 5.2.9 on 2025-12-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0007_airport_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='image',
        ),
    ]
