# Generated by Django 6.0 on 2025-12-16 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightAPIImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerName', models.CharField(max_length=50)),
                ('rawPayload', models.TextField()),
                ('importedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNumber', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('scheduledDeparture', models.DateTimeField()),
                ('scheduledArrival', models.DateTimeField()),
                ('airlineCode', models.CharField(max_length=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_flights', to='airports.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_flights', to='airports.airport')),
            ],
        ),
        migrations.CreateModel(
            name='FlightStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldStatus', models.CharField(max_length=50)),
                ('newStatus', models.CharField(max_length=50)),
                ('changedAt', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='GateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateCode', models.CharField(max_length=10)),
                ('terminal', models.CharField(max_length=10)),
                ('boardingOpenTime', models.DateTimeField()),
                ('boardingCloseTime', models.DateTimeField()),
                ('assignedAt', models.DateTimeField(auto_now_add=True)),
                ('releasedAt', models.DateTimeField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
    ]
