# Generated by Django 6.0 on 2025-12-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='terminal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
