# Generated by Django 6.0 on 2025-12-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_gate_flight_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='boarding_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='boarding_open',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
